import discord

async def ArcadeLoreExplained(interaction):
  loreEmbed = discord.Embed(title="Arcade Lore", description="So your interesed in the sekai lore. To be honest there isnt that much lore. Only on how i discover the sekai. It was on a date with Lilliya a girl i dated and became a couple with her. But let me explain a few things. Lets talk short about how i found my sekai through untitled. Some interesed sekai facts. How does the sekai look an short description. As last future updates. Also yeah the image was taken by arcade miku recently outside the arcade at night of me while im pregnant. It looked cute so i thought why not use it. ", color=0x249b8f)
  loreEmbed.set_image(url="https://cdn.discordapp.com/attachments/805518420081770516/1124273240626442351/ImgCreator.ai_An_cute_pregnant_girl_That_has_her_hair_in_a_ponytail_sky_blue_hair_color_in_tokyo_with_her_boyfr6.png")
  loreEmbed.add_field(name="How did i learn of my sekai or unitled", value="I think if it wasnt for Lilliya  that i never would have noticed. We were on date and traveling in the metro. I was laying with my head on her shoulder when i got a notification. A new song was added untitled. Lilliya asked me to play and there we went. Yep i still think we went both since i was laying with my head on her shoulder. So and there i stood in an arcade all of the sudden with my date.", inline=False)
  loreEmbed.add_field(name="Some interested Sekai facts", value="Some sekai facts of this girly gamer sekai. My sekai is based around an arcade it seems likes. With arcade machines from games i like, play a lot and even ones that never existed, There is a recording studio for my content-creation life and even pokemons. The arcade also has a garden place where you can chill and talk. Its the place where people enter Also there is a huge world outside. First a pokemon world where you can chill with pokemons. but let me talk about some details further.", inline=False)
  loreEmbed.add_field(name="Sekai looks and layout", value="As told earlier we have a huge arcade ground with all types of different games and different variantons of games. There is a corner for pokeslows since im well a diva girl. The garden also has a pool and it always warm weather here. so chilling is a good choice there. As told there is a huge world outside the Arcade. There is a forest area where you can chill with pokemons and pat them. There is even a city after the forest area which is huge. There is where miku made the picture of me. Quite a nice city looks like tokyo a lot.")
  loreEmbed.add_field(name="Future updates", value="So there is some lore but not alot as of moment on typing. So keep an eye on the thread for it. Maby you see an update here and there. Like the songs i cover or make. Who knows. This place is too lively to not keep an eye on. Even for a preggie girl like me.", inline=False)
  loreEmbed.set_footer(text="🎀 Girly gamer sekai explained 🎀")
  await interaction.response.send_message(embed=loreEmbed)
