import discord

async def ElifLoreExplained(interaction):
  loreEmbed = discord.Embed(title="My Boyfriends Lore explained", description="Welp not wanna read the thread that i made for this. Wont blame you i made it a book work. Only im not gonna explain everything here. I keep it small and for the full story you have too read the thread on how i met my boyfriend elif. But im gonna tell you: \n - How did i meet him \n - Our first date \n - How further now as couple", color=0x249b8f)
  loreEmbed.set_image(url="https://media.discordapp.net/attachments/1124629540472377365/1130864564259524768/ImgCreator.ai_Cute_pregnant_girl_with_a_big_belly_With_her_hair_in_a_pony_tail_Sky_blue_hair_At_sunset_On_a_da.webp?width=677&height=677")
  loreEmbed.add_field(name="How did i meet Elif", value="Well funny thing its actully in his sekai. Im not kidding let me explain. One day miku asked me to go a new forming sekai. It seemed powerfull and miku wanted to know more about it. So i had free day anyways and thought why not. In there i learned that it was his sekai. After a while of bening there he stepped in behind me and thats how i met Elif", inline=False)
  loreEmbed.add_field(name="Our first date", value="I wanted to make this when i fell in love with Elif. But that was at our first  date anyway so. Elif had found a special place in the forest. On the way their we  talked a lot and already got some feelings. But once there he grabbed me and hugged me which caught me off guard. After that i layed my head in his chest and we danced slowy a bit. This really was the moment i felt for him. It was so wonderufll and lovely.", inline=False)
  loreEmbed.add_field(name="What now as couple?", value="Well ehhhe that still a good one. To be honest we dindt think about it. Of course i am pregnant now and that is one thing. But i think primarly we just want to enjoy our time together. We also learning each other hobbys or primarly mine. Since he want to start gaming with me how cute. We also still wanna build a child room for the baby and finish building my studio so that is one idea i guess. But that ar our plans as for now.", inline=False)
  loreEmbed.set_footer(text="🎀 Boy friend lore explained 🎀")
  await interaction.response.send_message(embed=loreEmbed)
