import discord

async def LoreExplained(interaction):
  loreEmbed = discord.Embed(title="Your pregnant girl Elise her lore explained", description="Well ehhhe as i pat my belly you had a question? How does my lore work well that is a good one. Let me explain a few subjects. This preggo is gonna explain her lore in how this all happend. Im also gonna tell where you can find my lore. As last i will tell you how the order is for this pregnant girl her lore. Hope you enjoy but grab some popcorn and a drink", color=0x249b8f)
  loreEmbed.set_image(url="https://media.discordapp.net/attachments/961512157726539847/1154766619558559796/LoreExplained.png?width=1205&height=677")
  loreEmbed.add_field(name="Lore Explained", value="It all started basically with a weird dream. But my lore can be found in <#1152967259225075803>. There you can find serveral posts in a forum channel. Each posts basically explains a bit of lore. \n There is the Dream lore where i got my transformations, How i met Elif, My sekai looks?, My own sekai and as last ofcourse the pregnancy? So that explains how my lore works and how i got transformed into the girl that i am today ", inline=False)
  loreEmbed.add_field(name="Forum post system explained", value="Once i made my lore more was added and more. First it went to a thread system and now into a forum post system. Why you may ask. To prevent an cognitive overload once you open elise-lore. So there are multiple forumposts which each their own piece of lore. As of this moment im reworking the lore and rest of the discord into my v2.2? look so keep an eye out. The lore can be found in <#1152967259225075803>.", inline=False)
  loreEmbed.add_field(name="Order explained", value="Now ofcourse comes the question? Preggie girl Elise how is the order of your lore since they all stand through each other? Great question let me explain \n 1. The story of the transformation and the Mark *This is my dream where i got transformed* \n 2. The Arcade sekai. *Not long after i got my transformation i also got my own sekai* \n 3. Is how did Elise join Leo/Need *My first look i got was that from Leo/Need so i first joined the school sekai*", inline=False)
  loreEmbed.add_field(name="", value="4. After this comes The joruney onto the stages *After this i got my MMJ dress and became a idol* \n 5. The story of an cinema *A weird twist in the street sekai and a performance lead to my VBS dress* \n 6. A magical musical evening *A musical evening in the wonderland sekai showed me a plushie who had my dress* \n 7. A weird twist in the empty sekai. *A personal story lead to a suprise and a new dress* \n 8. After this is met my Boyfriend *So the lore where i told you the story of my boyfriend sekais* \n 9. As last is the pregnancy lore *Well you need an boyfriend to get pregnant right?*", inline=False)
  loreEmbed.add_field(name="Updates", value="There is still a chance your preggie girl will give updates to her lore!. So make sure to keep an eye out on the posts. You might find a new update here and there ", inline=False)
  loreEmbed.set_footer(text="🎀 The pregnant girl her lore explained 🎀")
  await interaction.response.send_message(embed=loreEmbed)
