import discord

async def PregnantLoreExplained(interaction):
  loreEmbed = discord.Embed(title="Pregnancy Explained", description="Your interesed in how a girl like me can get a pregnant. Well i dindt expect it either. Also for this is a lore thread that you can read if you want. I will explain it a bit in short here. Also Elif loves to take pictures of me and the one in the image is one of them. I thought it looked cute but oh well....", color=0x249b8f)
  loreEmbed.set_image(url="https://cdn.discordapp.com/attachments/805518420081770516/1124273221475258379/ImgCreator.ai_Cute_pregnant_girl_With_her_hair_in_a_pony_tail_Sky_blue_hair_As_gamer_girl_gaming_with_her_boyfr.png")
  loreEmbed.add_field(name="How can i get pregnant", value="We think Elifs sekai had something to do it with it. Well as couple we did it before ofcourse but it never got me pregnant. But the one time in his sekai and well after that i became sick. It lined up too well. Yeah i also never did it with an other man. The only other one i eveer had seks with was Lilliya. Were even friends with benefits still but dont use it that much since well i have a boyfriend. But how long is this gonna take then?", inline=False)
  loreEmbed.add_field(name="Expected lenght of my pregnancy", value="Well i dont think its the usual 40 weeks that people experince. Accdoring to the Elfs time works differntly in Elifs sekai. They are usually pregnant for 3 years in our time. But they dont know how long a human would be pregnant. Im also still suprised people can see my belly outside of his sekai. So the duration is somewhere from 3 years to how ever long we know. But why did we keep it then.", inline=False)
  loreEmbed.add_field(name="Why we decided to keep me pregnant", value="I know it sounds weird but there are 2 things. 1 I really had a dream of this ever happening. I mean i dindt expected as trans girl. I already layed peace with it that i couldnt in my lifetime. But once i became sick and we found out i was pregnant we were really happy. Here is were 2 comes. We arent sure if i can get pregnant again. Im 2 months as currently of typing this. But we decided to rather sit this one out and not bening able to get me pregnant again. Instead of an arbortion and then trying again with maby some succes.")
  loreEmbed.set_footer(text="🎀 My pregnancy explained 🎀")
  await interaction.response.send_message(embed=loreEmbed)
